export const theme = {
  gray700: 'var(--color-gray-700)',
  gray600: 'var(--color-gray-600)',
  gray500: 'var(--color-gray-500)',
  white: 'var(--color-white)',
  black: 'var(--color-black)',
  mainOrange: 'var(--color-main-orange-default)',
  subYellow: 'var(--color-sub-yellow)',
  subLightblue: 'var(--color-sub-lightblue)',
  subPurple: 'var(--color-sub-purple)',
  bgGradientBlue: 'var(--color-gra-bg-blue)',
  bgGradientOrange: 'var(--color-gra-bg-orange)',
  lineGradientYellow: 'var(--color-gra-line-yellow)',
  lineGradientBlue: 'var(--color-gra-line-blue)',
  lineGradientPurple: 'var(--color-gra-line-purple)',
  stateError: 'var(--color-state-error)',
  stateSuccess: 'var(--color-state-success)',
};
