name: Sync to Fork

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-to-fork:
    runs-on: ubuntu-latest
    if: github.repository == 'Central-MakeUs/status-front'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          git config user.name "mkki"
          git config user.email "devmkki@gmail.com"

      - name: Push to fork
        run: |
          git remote add fork git@github.com:mkki/status-front.git
          git push --force fork main

      - name: Cleanup remote
        if: always()
        run: |
          if git remote | grep -q "^fork$"; then
            git remote remove fork
          fi